server:
  port: 8000

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #驱动
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: admin
  #jpa:
   # hibernate:
    #  ddl-auto: update   #自动更新
    #show-sql: true        #日志中显示sql语句
#模板
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
#    mode: HTML5
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#MVC
  resources:
      static-locations: classpath:/static,classpath:/templates/index/
  application:
    name: simple-client
  security:
    user:
      name: user
      password: admin


#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      jdbc-url:
#      max-lifetime: 1765000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
#      maximum-pool-size: 15  #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)




#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.del.servermongo.model


#配置日志
logging:
  #配置日志文件路径
  path: classpath:log
  level:
    com.del.test: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: debg
#    org.hibernate: error

# 开发环境配置
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false
    username: root
    password: admin
#    spring.data.mongodb.uri=mongodb://root(userName):root(password)@localhost(ip地址):27017(端口号)/gis(collections/数据库)
  data:
    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      username:
#      password:
#      database: sso-test
#      uri: mongodb://root(userName):root(password)@localhost(ip地址):27017(端口号)/gis(collections/数据库)
      uri: mongodb://127.0.0.1:27017/sso-test

# 测试环境配置
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://rdsdhymc6hu2u0854dzny.mysql.rds.aliyuncs.com:3306/bianmin_114?characterEncoding=utf-8&useUnicode=true
    username: bianmin_user
    password: abcd_123

# 生产环境配置
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/
